// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba1.Server;

#nullable disable

namespace Prueba1.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230126231242_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba1.Shared.Controllers.Actores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actores");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.BlazorPeliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnCartelera")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha_de_lanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("costo_pelicula")
                        .HasColumnType("int");

                    b.Property<string>("poster")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.GeneroPelicula", b =>
                {
                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int?>("PeliculasId")
                        .HasColumnType("int");

                    b.HasKey("GeneroId", "PeliculaId");

                    b.HasIndex("PeliculasId");

                    b.ToTable("GenerosPeliculas");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.PeliculaActor", b =>
                {
                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int?>("ActoresId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int?>("PeliculasId")
                        .HasColumnType("int");

                    b.Property<string>("Personaje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeliculaId", "ActorId");

                    b.HasIndex("ActoresId");

                    b.HasIndex("PeliculasId");

                    b.ToTable("PeliculasActores");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.GeneroPelicula", b =>
                {
                    b.HasOne("Prueba1.Shared.Controllers.Genero", "Genero")
                        .WithMany("GenerosPelicula")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prueba1.Shared.Controllers.BlazorPeliculas", "Peliculas")
                        .WithMany("GenerosPelicula")
                        .HasForeignKey("PeliculasId");

                    b.Navigation("Genero");

                    b.Navigation("Peliculas");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.PeliculaActor", b =>
                {
                    b.HasOne("Prueba1.Shared.Controllers.Actores", "Actores")
                        .WithMany("PeliculasActor")
                        .HasForeignKey("ActoresId");

                    b.HasOne("Prueba1.Shared.Controllers.BlazorPeliculas", "Peliculas")
                        .WithMany("PeliculasActor")
                        .HasForeignKey("PeliculasId");

                    b.Navigation("Actores");

                    b.Navigation("Peliculas");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.Actores", b =>
                {
                    b.Navigation("PeliculasActor");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.BlazorPeliculas", b =>
                {
                    b.Navigation("GenerosPelicula");

                    b.Navigation("PeliculasActor");
                });

            modelBuilder.Entity("Prueba1.Shared.Controllers.Genero", b =>
                {
                    b.Navigation("GenerosPelicula");
                });
#pragma warning restore 612, 618
        }
    }
}
